apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: claims-db-creds
  namespace: insurance-claims
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: db-credentials
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: "apps/claims-service/db"
      property: "user"
  - secretKey: password
    remoteRef:
      key: "apps/claims-service/db"
      property: "pass"
